### ISSUE TITLE
Heatmap or aggregate means of displaying locations

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-blurred-location-display#21]
- explore heatmap or aggregate means of displaying locations that, for example, fall in the same grid square, using varying shades to indicate density

-  explore above heatmap display (configurable with a constructor parameter) with ability to click on a grid square to expose a list of points within that square

I guess to get started : 

1.  We should make a function to get current grid square coorindates .

2. Make a function which uses the API to return the number of markers within that grid square .

@jywarren ...what should we do next ?

**Comment by sagarpreet-chadha** [comment]
Found your comment here : https://github.com/publiclab/leaflet-blurred-location-display/issues/10#issuecomment-442210913

Breaking out an issue to develop ways to show multiple data points that have been blurred as a kind of "heat map" or chloropleth?

https://deutchland.maps.luftdaten.info/#4/35.03/5.40 does this in Leaflet, although with a hex grid...

![screen shot 2018-11-27 at 3 45 15 pm](https://user-images.githubusercontent.com/24359/49110467-9759f180-f25b-11e8-8fb8-66db589ea972.png)

There are for sure Leaflet chloropleth map plugins out there!

**Comment by sagarpreet-chadha** [comment]
@jywarren 

chloropleth seems like a great idea !
But this would be like an overlay layer , right ?  (and will be not related to grid-squares) . 

**We need to figure out how to create geoJSON , and then we can make this .** 

Example  from https://leafletjs.com/examples/choropleth/ : 
<img width="906" alt="screenshot 2019-02-06 at 1 34 00 am" src="https://user-images.githubusercontent.com/14952645/52300992-509d1c00-29af-11e9-859a-66d96c30804b.png">

We can create **static** geoJSON from this site : http://geojson.io/#map=4/36.67/-92.81

**Comment by jywarren** [comment]
I think we could use the idea of a chloropleth but using our own grid, what
do you think?

**Comment by sagarpreet-chadha** [comment]
The only problem is the generation of geoJson . 

Also , if somehow we generate for lets say zoom level 5 , when we zoom in --- the size of grid square changes and we need to remove previous chloropleth layer and using new geoJson input generate new one .

**Comment by sagarpreet-chadha** [comment]
@jywarren ... what do you think of a heatmap , maybe as an overlay layer ?

I guess the advantage of using heatmap would be that we have to fetch data **once** !
As we zoom in/out the heatmap layer adjusts itself relatively .

See this Demo : http://leaflet.github.io/Leaflet.heat/demo/

**Comment by jywarren** [comment]
Hi, Sagarpreet, i wonder if we could generate geoJSON based on our grid, and color that? 

The problem with the heatmap is that it will work with the truncated location, not the "region" within which it falls. I think I'd prefer to try to just apply fill color to the grid we already draw with LBL, does that make sense?

Also noting - I just enabled Dependabot, which should help us keep our dependencies up to date. It works best with tests, because each PR it opens will run against the tests. But if you can try these PRs out and merge them, it'll work even without our having the tests just yet. Take a look!

**Comment by jywarren** [comment]
Hi, Sagarpreet, i wonder if we could generate geoJSON based on our grid, and color that? 

The problem with the heatmap is that it will work with the truncated location, not the "region" within which it falls. I think I'd prefer to try to just apply fill color to the grid we already draw with LBL, does that make sense?

Also noting - I just enabled Dependabot, which should help us keep our dependencies up to date. It works best with tests, because each PR it opens will run against the tests. But if you can try these PRs out and merge them, it'll work even without our having the tests just yet. Take a look!

**Comment by sagarpreet-chadha** [comment]
Hi @jywarren ,

Kindly confirm this 😄 :

We need to change the color of the center rectangle (which is now by default red color) to different colors according to the number of markers the center_rectangle has , right ?
We can follow similar color pattern maybe : 
<img width="90" alt="screenshot 2019-02-19 at 3 25 05 pm" src="https://user-images.githubusercontent.com/14952645/53006083-8daae900-345a-11e9-8525-44b6f91cf419.png">

Also to add a pop up which shows the number of markers (irrespective of precision) in the center_reactangle : 
_[Rectangle in our case ! ]_
<img width="402" alt="screenshot 2019-02-19 at 3 28 22 pm" src="https://user-images.githubusercontent.com/14952645/53006343-0d38b800-345b-11e9-9d43-72d23afedf4b.png">

**Comment by jywarren** [comment]
This sounds fantastic. We should show the color key too!

**Comment by sagarpreet-chadha** [comment]
Awesome ! On it once PR #42 gets reviewed :smile: .
