### ISSUE TITLE
Weekly Community Check-in #23 - "Don't Give Up"

### ISSUE THREAD

**Issue by aashna27** [publiclab/leaflet-blurred-location-display#78]
Hi everybody :smiley: !

We all at Public Lab :balloon:  - learn, grow, work, brainstorm ideas, contribute together so why not share about our _weekly goals and the awesome work_ we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal :dart: . You are also welcome to share fun-fact :smile: , new ideas :bulb: , your learning goals :ballot_box_with_check: .

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. :100:

If you're new here, welcome, and please comment a _Hello_ below, we would love to work with you. If you're looking for new issues, please try some of our [first-timers-only](https://code.publiclab.org/#r=all) issues.

We're SO EXCITED to have your help!

**Is there anything, you would like to share with us from past week's work? What is your plan for this week?**

If you have not planned yet, just leave a Hello! :wave: so that we know that you are in sync with us :arrows_clockwise: and doing well!

The coming weeks will be full of code :computer: , tasks :spiral_notepad:, fun :tada: and excitement :smiley:!!

As always, if you're waiting for a review, or if you're stuck, please request help here OR leave a comment with @publiclab/mentors @publiclab/reviewers for some input. :raised_hands:

#### Gitter

Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up [there](https://gitter.im/publiclab/publiclab) for these updates or just to join the conversation. You can also join us through http://publiclab.org/chat :speech_balloon:.

### _This week's theme_ 

The theme for this week is - "Share your challenges and grow together". :clinking_glasses:  We all are part of this supportive community wherein we take tasks that are totally new to us and every task or some particular ones bring new challenges, share your recent challenges and how you kept fighting to get your task done and experienced that gush of happiness.

Recently I faced it with "Text over Image" feature in image sequencer wherein things were consistently messy, sometimes the image disappeared and the other times the font. But this was my feature, and I was not ready to stop. :bowing_woman:  I kept on trying posts and debugging for issue areas. Finally, the persistence paid off and I made it!! :tada:  I have learned that _a dead end is only when you stop trying_. If you want something, set your mind to it keep on challenging yourself to do it.

For the soc students especially, the months ahead will be a challenge but follow "Plan, conquer and enjoy" :dancer: 

I would love everyone to share their experiences.

You can find our list of previous check-ins [here](https://github.com/publiclab/plots2/issues/5627) 

## Note to Summer of Code interns:

Hi, we request all the SoC students to include the below-mentioned points in their check-in comment:
- FTOs created in the previous week
- Progress for your project
- Upcoming week's goals 
- PR reviewed by you in the previous week
- Work completed last week.
- What things you did collaboratively last week? This is really important we want team spirit.
It is like a weekly scrum. Be flexible. 
- Feel free to tell us about your absence too, if you're taking a break.
- Issue/PR you're struggling with (if any)

With FTOs and PR reviews, we are seeking to develop a much more friendly and collaborative platform. We want you all will involve people in your project. You all will develop skills like leadership along the way.

Thank you!

**Comment by aashna27** [comment]
@mohitRJranjan @milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @geekychaser @shubhscoder @sidntrivedi012 @SidharthBansal @cesswairimu @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1, @uzorjchibuzor, @eli6, @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @romanrodriguez @Dhiraj240 @codeIriss @rishabhc32 @chirag-singhal @IgorWilbert @vrk99 @pdurbin @HarshKhandeparkar @aashna27 @niravasher @marieram @gauravano @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @subhahu123 @An0u @Jaya738 @mgroovyank @shreyateeza @TANGL3SIT3S @nazeem1988 @karunagoyalk @Nirvikalpa108 @cassianoblonski @EngrEric @Anjalizi @GettyOrawo @coderbeetle @corbettbw @govindjeevan @gautamig54 @daddyjab @emestabillo @letnewKid @srujana121 @jazdao @ChinwenduSilvia @aggarwal19 @Jenniline @madelinejones @helenatxu @richa031 @fabsar @kuja24 @megha070 @Aarabhi2017 @Manvi07 @siddhishree @Julius26 @VinneyJ @sonali9696 @rarrunategu1 @coreytegeler @labseven @milomacphail @CleverFool77 @ananyaarun @ananya @divyabaid16 @publiclab-mimi @shubhi2000 @Priyak5 @vaarigupta @techchic @ananya @hc-barker @edwd42 @PritiShaw @themonster2015 @supriya-kotturu @AnthoniaOkafor @scheleon @mahmodHammad @santushk @jillpena @stoic-plus @starkblaze01 @aSquare14 @vaarigupta @alonpeer @madeofhuman @ibnjunaid @HarshKhandeparkar @aashna27 @harshithpabbati @niravasher @mmmelissa @rarrunategu1 @daz @UNnamed66 @GauravJ3 @Greg-Tarr @Sanscripter @hodbadger

**Comment by gauravano** [comment]
@publiclab/community-reps @subhahu123 @An0u @Jaya738 @mgroovyank @shreyateeza @TANGL3SIT3S @nazeem1988 @karunagoyalk @Nirvikalpa108 @cassianoblonski @EngrEric @Anjalizi @GettyOrawo @coderbeetle @corbettbw @govindjeevan @gautamig54 @daddyjab @emestabillo @letnewKid @srujana121 @jazdao @ChinwenduSilvia @aggarwal19 @Jenniline @madelinejones @helenatxu @richa031 @fabsar @kuja24 @megha070 @Aarabhi2017 @Manvi07 @siddhishree @Julius26 @VinneyJ @sonali9696 @rarrunategu1 @coreytegeler @labseven @milomacphail @CleverFool77 @ananyaarun @ananya @publiclab-mimi @shubhi2000

**Comment by gauravano** [comment]
@Priyak5 @techchic @ananya @hc-barker @edwd42 @PritiShaw @themonster2015 @supriya-kotturu @AnthoniaOkafor @scheleon @mahmodHammad @santushk @jillpena @stoic-plus @starkblaze01 @aSquare14 @vaarigupta @alonpeer @madeofhuman @ibnjunaid @aashna27 @harshithpabbati @mmmelissa @rarrunategu1 @daz @UNnamed66 @GauravJ3 @Greg-Tarr @Sanscripter @hodbadger @alaxalves @becomingajunior @monsij

**Comment by cesswairimu** [comment]
@aashna27 awesome check-in  :tada: 
Hi all :wave: 

 For the past two weeks I have been working on upgrading Mapknitter from Rails 3.2 to 4.2. A lot of  "learning experiences"(this is what I call challenges :wink: ). However frustrating/exciting this process has been, everyday I get something to work/ fix a few  tests.

Four days ago  I got everything to work (functionality wise) apart from the Image upload feature. Since then, no progress :expressionless: I have been trying to fix this functionality since then, I have followed a couple of leads/ rabbit holes which have led me nowhere :woman_facepalming:  but am still on it,  working on it right now actually, no giving up. Which reminds me if anyone understands the image upload functionality of Mapknitter and would love to take a look at my branch please ping me. 

Nice week ahead everyone :balloon:

**Comment by sashadev-sky** [comment]
hi all!

I have been working on a new exporter system for Mapknitter, along with a few other contributors. This is a challenge for me as I have never implemented an exporter system before, but @jywarren has broken it down for me along the way into clear, small tasks. It has been really rewarding to make progress on this from my end and also work together with others to contribute pieces of it that are starting to come together! Thanks!

**Comment by CleverFool77** [comment]
Hi 
This is lekhika dugtal.
I'll be working on UI Improvements of project along with @gautamig54.
I'll be writing down some of points as mentioned by @SidharthBansal and @gauravano in Earlier check ins.
Last week I started off my with work for summer of code UI Imporvements and had some of my `PRs merged`. 
* Cards for people section `people` https://github.com/publiclab/plots2/pull/5740
* On tags section `/tags` https://github.com/publiclab/plots2/pull/5766
* map in people section `/people` https://github.com/publiclab/plots2/pull/5754

These are some of the merged PRs which were fixes for bootstrap4 upgrade
* https://github.com/publiclab/plots2/pull/5756
* https://github.com/publiclab/plots2/pull/5755

The below are the work in progress PRs or those PRs which are still under the review process done for summer of code.
* `/people section` https://github.com/publiclab/plots2/pull/5765
* `/questions section` https://github.com/publiclab/plots2/pull/5787
* `/search section` https://github.com/publiclab/plots2/pull/5747

These are some of the open PRs for bootstrap4 upgarde in last week.
* https://github.com/publiclab/plots2/pull/5767 
* https://github.com/publiclab/plots2/pull/5772

One of the Issues I opened last week.
https://github.com/publiclab/plots2/issues/5741

Me and @gautamig54 are collaborating. It can be seen that I'm working on various section side by side. It's because we have divided our parts in section and continuing moving forwards altogether.

We have are having huge discussions with  @jywarren.
If anyone is interested, they can join us at any of the interested links below for exciting discussions on various section .
* `questions section` https://github.com/publiclab/plots2/issues/5733
* `search section` https://github.com/publiclab/plots2/issues/5708
* `people section` https://github.com/publiclab/plots2/issues/5707

One general Issue and central hub for all discussions ? 
https://github.com/publiclab/plots2/issues/5739

You can see the progress of projects : - 
https://github.com/publiclab/plots2/projects/10

cc : Mentors @jywarren @gauravano @rexagod @cesswairimu @souravirus @milaaraujo 
cc : @gautamig54

**Comment by ananyaarun** [comment]
Hi Everyone !!
I'm Ananya an outreachy intern with Public Lab, working on Leaflet Environmental Layers repository.
Here is the jist of my project https://github.com/publiclab/leaflet-environmental-layers/issues/173

## Update on last week's progress -

### FTO's created by me
- https://github.com/publiclab/leaflet-environmental-layers/issues/189

### Progress of my project

here are some issues/PR's I worked on last week.

- https://github.com/publiclab/leaflet-environmental-layers/issues/180
- https://github.com/publiclab/leaflet-environmental-layers/issues/182
- https://github.com/publiclab/leaflet-environmental-layers/issues/186
- https://github.com/publiclab/leaflet-environmental-layers/issues/188
- https://github.com/publiclab/leaflet-environmental-layers/issues/184

- https://github.com/publiclab/leaflet-environmental-layers/pull/185
- https://github.com/publiclab/leaflet-environmental-layers/pull/163
- https://github.com/publiclab/leaflet-environmental-layers/pull/183

### PR's reviewed by me

- https://github.com/publiclab/plots2/pull/5788
- https://github.com/publiclab/leaflet-environmental-layers/pull/179
- https://github.com/publiclab/leaflet-environmental-layers/pull/191

### Work done last week

Last week I found an error in the installation of the LEL repo on my local and with the help of @sagarpreet-chadha we traced which PR was causing that error and fixed it. The fix involved some issues with java script ordering in the main html file and some redundant code that was accidentally merged.

I also started with some revamping UI related issues. Looked at different Leaflet plugins and understood the goals of my project better :)

### Goals for next week

Next week I would like to fix some issues i found and opened last week wrt menu organization of the LEL layers.
I'll also open a few FTO's and continue helping and reviewing PR's as much as i can !!

Thanks everyone !!!
Have a great week ahead :smiley:

**Comment by jywarren** [comment]
> But this was my feature, and I was not ready to stop. 🙇‍♀

Great attitude @aashna27 !!!

@cesswairimu - do you have an issue open where you're working through the upload system? I think one complicating factor is that the images are stored in Amazon S3 in production, but locally for development, both using the Paperclip gem. But the system is similar (except for Amazon S3) to the `plots2` image storage!

Great to see everyone working together! Please give a shout out if you'd like to ask others to review your work or help you get "un-stuck"!

**Comment by IshaGupta18** [comment]
Hey Everyone!

I am Isha Gupta and I am working with @namangupta01 on the project Sensor Data upload and Display Library for GSoC this summer.

Work is going on at https://github.com/publiclab/simple-data-grapher

We have the basic functionality up for a long time now, some of my PRs merged within the last couple of weeks are:

- https://github.com/publiclab/simple-data-grapher/pull/28
- https://github.com/publiclab/simple-data-grapher/pull/23
- https://github.com/publiclab/simple-data-grapher/pull/18
- https://github.com/publiclab/simple-data-grapher/pull/9
- https://github.com/publiclab/simple-data-grapher/pull/1

All of this code was written from the very scratch, since its a new library.

Right now, work is being done to restructure the existing code and also improve upon the graph features and discussions are being held on:

- https://github.com/publiclab/simple-data-grapher/pull/29
- https://github.com/publiclab/simple-data-grapher/issues/30
- https://github.com/publiclab/simple-data-grapher/issues/22

Since its a new library, once we have a little more code in place, FTOs will be opened and newcomers are more than welcome to explore the library in the meantime.

This week, I aim to get the browsable range-slider up and running, apart from improving some structure of the code and making the graphs more conclusive!

Have a great week everyone!

**Comment by jywarren** [comment]
Hi all! I wanted to share some cool graphs I made back in March  - using this using a system called hercules -- https://github.com/src-d/hercules

It's designed for making a whole bunch of different types of graphs, but a few that interested me - here's one that shows (for plots2) what year code was written in, over time:

![image](https://user-images.githubusercontent.com/24359/58509696-27beb380-8165-11e9-9e82-1720d17244b7.png)

There are a lot more graphs in the comments on this post, too (sorry, i thought it was related enough to add in comments there, and I didn't do enough analysis to make a whole new post). 

https://publiclab.org/notes/gauravano/03-29-2019/software-community-growth-through-first-timers-only-issues#c24272

I can also re-generate them with more recent data if people are interested; it took quite a while to get it all installed and running, and a while to crunch the data as well, but i have it all set up now, so it's not so bad anymore.

**Comment by jywarren** [comment]
Also! This is cool! "Used by" is now a GitHub feature:

![image](https://user-images.githubusercontent.com/24359/58512841-188f3400-816c-11e9-86a2-10bcd48815da.png)

**Comment by Divy123** [comment]
Very nice theme @aashna27 .  I still remember when I was refactoring the core API of sequencer to provide only single image support per  sequencer, it was a whole bunch of errors, sometimes in running the code successfully, sometimes during changing the tests. But ultimately, the next version release was something that was such a big moment for me.

And this time also during SoC period, lots of challenges are there, but we are all ready to again learn something new out of it.

Also @jywarren I would suggest if we can utilize the new sponsor feature of GitHub. Some organisations have addded this:

https://github.com/rtfd/readthedocs.org/pull/5729

https://github.com/prettier/prettier/blob/master/.github/FUNDING.yml

What do you think upon this?

**Comment by cesswairimu** [comment]
Thanks @jywarren, I  will compare with the plots2 image storage. I will also open an issue for the same and ping you thanks.

**Comment by cryptoclidus** [comment]
Hi All!
I'm Jasmine and new to the publiclab Github. This week I completed my first FTO issue and am just getting the hang of using Github repositories.

My major challenge is overcoming the overwhelming feeling that there is just so much to learn right now! I entered here wanting to figure out how to enable a live capture from my raspberry pi's ip camera feed and complete the data processing on a computer, for a project I'm working on (https://publiclab.org/notes/jenjimah/04-07-2019/horticultural-spectroscope-upgrade-planning). But it's definitely going to take me some time to get up to speed. I only have completed one intro Computer Science course so far so a lot of this is new for me. My background is mainly in plant science!

**Comment by jywarren** [comment]
Welcome, @cryptoclidus! Congrats on your first FTO 🙌 

Very cool to hear about your raspberry pi work. Do check out https://publiclab.org/pi-builder and https://github.com/publiclab/pi-builder/ !

Plant science FTW! 🌱 

@IshaGupta18 I opened an issue to start collecting resources here: https://github.com/publiclab/plots2/issues/5794

**Comment by jywarren** [comment]
I also wanted to ask if @publiclab/mentors or @publiclab/soc folks might be able to help @Divy123 with some issues in WebAssembly -- it's a bit outside my area of expertise but it's part of a really interesting project to optimize image processing in `image-sequencer`: https://github.com/publiclab/image-sequencer/issues/400#issuecomment-497088314

@Divy123 would love some help with this, and I'd really appreciate the support too!

**Comment by cryptoclidus** [comment]
Thanks @jywarren ! I actually followed your [tutorial](https://publiclab.org/notes/warren/04-20-2018/prepare-an-sd-card-for-a-raspberry-pi-camera-from-scratch?_=1559161113) to get the pi all set up. I tried pi-builder first, but it didn't work so I ended up using the USB method, now it works. Turns out I didn't have Bonjour services installed (I had iTunes though!?)

**Comment by gauravano** [comment]
Hi everyone, we are planning to hold an Open Call for Summer of Code interns where they can ask their questions, share their experiences and much more. Also, we would be discussing some topics like Testing, reviewing process, Unstable usage, etc. 

The Open call will take place on June 4, 2019, Tuesday. Please express the time you're comfortable with  https://www.when2meet.com/?7871820-tR6Vk 

Looking forward to meeting you all :smile: .

**Comment by sashadev-sky** [comment]
Just wanted to share a cool and inspiring article about a team of students that met online and virtually collaborated to build a rocket: https://www.wsj.com/articles/bored-teenagers-found-each-other-online-and-built-a-rocket-to-launch-into-space-11559143865

**Comment by gauravano** [comment]
Hi, anyone interested in opening a new check-in?

**Comment by aSquare14** [comment]
I'll do it ! :)

**Comment by gauravano** [comment]
Great. Please go ahead and you can refer to https://github.com/publiclab/plots2/blob/master/doc/CHECKINS.md. Thank you!

**Comment by gauravano** [comment]
Hi, new check-in is open at https://github.com/publiclab/plots2/issues/5828. Thanks everyone!!
